### ISSUE TITLE
stuck in "waiting for lobby"

### ISSUE THREAD

**Issue by snowleopardd** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#18]
what am i doing wrong? i compiled it straight from github, but it doesn't find the lobby

**Comment by Baseult** [comment]
which server do you play on?

**Comment by snowleopardd** [comment]
> which server do you play on?

LAS

**Comment by rocklee8899** [comment]
same happens to me, it's stuck on waiting for lobby (LAS server)

**Comment by Adamming123** [comment]
im playing on NA, same issue. stuck in waiting for lobby. I was used 1.2 as well. there is a button ''get names'' to refresh a lobby page is nice. but I cannot use 1.5.1

**Comment by Baseult** [comment]
Should be fixed now
