### ISSUE TITLE
Is it possible to have it ordered as players are ordered in champ select ?

### ISSUE THREAD

**Issue by Lyfhael** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#2]
Hey,

For example in champ select players are ordered like that : 
PlayerC
PlayerB
PlayerA
PlayerD
PlayerE

The tool will list Players, but not by their order in champ select
Is it possible to do that you think ?

**Comment by Baseult** [comment]
not possible by using the api only, sorry
