### ISSUE TITLE
What do I do?

### ISSUE THREAD

**Issue by SleepyLabrador** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#23]
Hi,

 I am new to github and I was wondering what exactly am I meant to do to run the program?

**Comment by JaworTM** [comment]
With this button you can run the code (if you have installed Visual Studio)
![obraz_2024-02-27_052746920](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/161356303/3291e517-18bf-4589-b94a-99b5a5b0d8a8)

**Comment by SleepyLabrador** [comment]
OK, I downloaded Microsoft Visual studio.

What now? would you be able to make a youtube video showing me step by step how to do it? I can compensate you for your time.

**Comment by YuanDou98** [comment]
![image](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/82554737/f3215569-5b44-4773-8f8c-7801d6ad667b)
Click here and download the zip.
