### ISSUE TITLE
Erroneous players shown in the lobby

### ISSUE THREAD

**Issue by JaworTM** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#24]
I restarted the program, the game, checked the code and nothing. Michauenko is my friend, but he is offline and I didn't play with him since I downloaded Baseult-Rev. After dodging it shows the same 2 players even with 1 player in lobby
![obraz_2024-02-26_182506483](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/161356303/3bf28f21-e985-4771-829b-c22c9f75c903)

EUNE server

**Comment by JaworTM** [comment]
![obraz_2024-02-26_183927343](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/161356303/c1efab36-559c-423d-915a-64ce89a0b0eb)
After joining game names are cloned and wrong

**Comment by Baseult** [comment]
Before joining a Lobby, open your DMs and make sure to close them all, otherwise it will show you the players from your dm list.

**Comment by JaworTM** [comment]
You solved my problem, thanks
