### ISSUE TITLE
safe after todays bans?

### ISSUE THREAD

**Issue by sinankivanc3131** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#26]
I have been using the lobby revealer app of baseult, unlike kbot it doesnt have 30+ functionalities, looks like just calls the official /champ-select riot api to get the names for your team. Anyone got banned for this? I have been using it for the last 1.5 years and never got banned but scared to use today

**Comment by Baseult** [comment]
It is most likely detected now. Use it at your own risk!

**Comment by sinankivanc3131** [comment]
Vow my rank 10 account just got banned, havent used it last 2 days but still got banned

**Comment by Baseult** [comment]
Bans are only for 2 weeks. You will be unbanned after that.
