### ISSUE TITLE
im sorry

### ISSUE THREAD

**Issue by readyztw** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#3]
good morning, sir. I know it's dumb asf, but can you please help me with this project. it's xerath SPELLAIMBOT but I believe targeting is not working properly, it uses .NET flamework and I'm not good at it. if you can check that screen capture module with CursorPos, it would be an awesome project for all of us. I'm so sorry for this kind of behavior from my side https://github.com/Peppers0/Xerath-Script-AimBot

**Comment by pilusoyyo** [comment]
bruhhh
