### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Gap6769** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#4]
Hi Beseult, thanks for your great work.

I was wondering if would be possible to modify one existing feature to use porofessor instead of u.gg. For me it would be very appreciate.

**Comment by Baseult** [comment]
Added with the latest update

**Comment by Gap6769** [comment]
> Added with the latest update

should I compile it my self? I can't see any link for download de .exe
