### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Moleite** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#6]
I saw the previous issue from DonBlaze 3 weeks ago, but for me the app was still working.
It stopped working this wednesday 13/11/2023, is it possible to fix it please?

(Did few changes some time ago on the buttons to have Porofessor / OP.GG / U.GG)

![image](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/17182585/73a8e694-30a8-45d7-a375-dd8f62c58cc6)

![image](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/17182585/efd6f586-2f69-4fda-b7ac-178c5ac78bb9)

> Consultez la fin de ce message pour plus de détails sur l'appel du débogage
> juste-à-temps (JIT) à la place de cette boîte de dialogue.
> 
> ************** Texte de l'exception **************
> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à GetSummonerNames.Form1.button_names_Click(Object sender, EventArgs e) dans C:\Users\regalia\workspace\Baseult-Rev-League-of-Legends-Lobby-Revealer\GetSummonerNames\Form1.cs:ligne 227
>    à System.Windows.Forms.Control.OnClick(EventArgs e)
>    à System.Windows.Forms.Button.OnClick(EventArgs e)
>    à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    à System.Windows.Forms.Control.WndProc(Message& m)
>    à System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    à System.Windows.Forms.Button.WndProc(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Assemblys chargés **************
> mscorlib
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4360.0 built by: NET48REL1LAST_C
>     CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> GetSummonerNames
>     Version de l'assembly : 1.0.0.0
>     Version Win32 : 1.0.0.0
>     CodeBase : file:///C:/Users/Moleite/Downloads/Release%20(1)/GetSummonerNames.exe
> ----------------------------------------
> System.Windows.Forms
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4341.0 built by: NET48REL1LAST_C
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4360.0 built by: NET48REL1LAST_C
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4084.0 built by: NET48REL1
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4360.0 built by: NET48REL1LAST_C
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4084.0 built by: NET48REL1
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Newtonsoft.Json
>     Version de l'assembly : 13.0.0.0
>     Version Win32 : 13.0.2.27524
>     CodeBase : file:///C:/Users/Moleite/Downloads/Release%20(1)/Newtonsoft.Json.DLL
> ----------------------------------------
> System.Management
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4084.0 built by: NET48REL1
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
> ----------------------------------------
> System.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4084.0 built by: NET48REL1
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.resources.dll
> ----------------------------------------
> System.Numerics
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4084.0 built by: NET48REL1
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4250.0 built by: NET48REL1LAST_C
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> System.Data
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4270.0 built by: NET48REL1LAST_C
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> mscorlib.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4084.0 built by: NET48REL1
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
> ----------------------------------------
> System.Windows.Forms.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.8.4084.0 built by: NET48REL1
>     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
> ----------------------------------------
> 
> ************** Débogage JIT **************
> Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
> application ou cet ordinateur (machine.config) doit avoir la valeur
> jitDebugging définie dans la section system.windows.forms.
> L'application doit également être compilée avec le débogage
> activé.
> 
> Par exemple :
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
> seront envoyées au débogueur JIT inscrit sur l'ordinateur
> plutôt que d'être gérées par cette boîte de dialogue.
> 
> 
>

**Comment by Baseult** [comment]
Fixed with the latest update
