### ISSUE TITLE
New riot IDs issue (v13.24)

### ISSUE THREAD

**Issue by Moleite** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#7]
Can you please add the new riot IDs # after the name of the players for multi searchs?
Some websites like OP.GG can find the player only if he is the only one to have the name.
But others like porofessor are not working anymore

**Comment by Tjonna** [comment]
This please!

**Comment by Moleite** [comment]
For developpers & tinkerers before the hotfix, or to help Baseult to fix the issue, here are some changes that can actually make it work :

"Player" class update :
![image](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/17182585/2820f9bc-3209-407a-a511-4eec2d7ce4c5)

"Getplayers" method update :
![image](https://github.com/Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer/assets/17182585/a17ed976-7d7e-4a15-a67c-95630a5d4cde)

Main issue is that I didn't handle all trackers site syntax for gamer tags, as each site is using it's own.
For my usage (Porofessor & OP.GG) it's working, but not all of them :
- "%23" separator is working for most trackers multi-search
- "-" separator is working for OP.GG mono-search.

Hope this helped.

**Comment by Baseult** [comment]
Fixed
