### ISSUE TITLE
Is this safe post-vanguard?

### ISSUE THREAD

**Issue by Crizzooo** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#9]
Hi, awesome work here. 

Just wondering if this program is now dangerous given the addition of Vanguard?

**Comment by Baseult** [comment]
Not sure yet. It only interacts with Riots API and doesn't read any memory, but still Vanguard could detect it running if Riots wants to. So I would recommend not to use it for a few weeks after Vanguard has launched, until we know more.
